-- 2026-08-07  Process costing: what each step of a part's routing costs per piece.
--
-- The routing already exists and nobody had to be asked for it. Parts."Process" is a JSON array
-- of process names in the order the part is made - 235 part rows, 1,117 steps, 92 distinct
-- process names - and it has been there since the part master was built. This file adds the one
-- thing missing from it: a number per step. Everything else on the two screens is arithmetic over
-- that number and quantities the system already records.
--
-- WHAT A COST BELONGS TO.
--   part number + process name. Not the Parts row. 220 part numbers occupy 235 rows because ten
--   numbers carry more than one revision, and those revisions do not share a routing - rev 01 of
--   07150-04036 plates black oxide, the unrevised row plates plain. Keying cost to the row would
--   mean a new revision starts with an empty cost sheet and somebody re-types twelve numbers that
--   did not change. Keying it to the number means a revision inherits the costs already entered,
--   and a step that only exists in one revision simply has no cost until someone enters one.
--
--   The cost of PLATING on a part is a property of the part and the process, and a drawing
--   revision is not by itself a reason for it to move. When it is a reason, the number gets
--   edited - and the history table below says who moved it and from what.
--
-- WHITESPACE IS NOT A SECOND PROCESS.
--   Eleven of the 92 process names appear in the routings both with and without a trailing space:
--   [HARDEN] and [HARDEN ], [STAMPING 1] and [STAMPING 1 ], [SWISS AUTO LATHE MACHINING] and the
--   same with a space. Stored raw, those are two keys, and a part costed under one spelling would
--   read as uncosted under the other. Every write is trimmed by trigger and the uniqueness index
--   folds case, so one process on one part can hold exactly one cost however it was typed.
--
--   The variants in Parts."Process" are NOT corrected here. Which of them is a typo and which is a
--   process somebody genuinely names differently is a person's call, and the trim on this side
--   makes both spellings land on the same cost either way.
--
-- WHAT IS NOT HERE.
--   No currency column. This system quotes in one currency - SalesOrder_Items.unit_price carries
--   none either - and a column that is 'MYR' on every row is a column that will be wrong the
--   first time it is not.
--
--   No effective dates. One live cost per part/process, and every calculation uses it. The
--   history table records what changed, when and by whom, so the trail is readable; it is not
--   joined back to value a job at the cost that applied the month it ran. That is a real feature
--   and a different shape of screen - it would put an "as of when" on every figure - and it was
--   considered and left out rather than half-built.
--
--   No cost breakdown. One number per step, which is what was asked for. Labour, machine hours
--   and an outsourced plater's invoice all land in the same figure. cycle_time already holds
--   seconds per part per process on 67 rows, so a rate-driven cost is available later without
--   this table changing shape - it would fill cost_per_pcs rather than replace it.
--
-- Safe to re-run. Preserves every existing row.
--
-- Run as the table owner:
--   docker exec -i supabase-db psql -U supabase_admin -d postgres -v ON_ERROR_STOP=1 \
--       < sql/2026-08-07_process_cost.sql

begin;

-- ---------------------------------------------------------------------
-- 1. Reading a routing that might not parse
-- ---------------------------------------------------------------------
--
-- Parts."Process" is text holding JSON, not a jsonb column, so nothing stops a bad value being
-- saved into it. All 235 rows parse today. If one ever does not, a plain `::jsonb` in the views
-- below would fail the whole query and every part would vanish from both screens because of one
-- bad row. This returns null instead, and the views left-join so that part still lists - with no
-- steps and a flag saying its routing could not be read.
--
-- pg_input_is_valid() would do this without a function, but that is PostgreSQL 16 and this is 15.

create or replace function jsonb_or_null(t text) returns jsonb
    language plpgsql immutable as $$
begin
    return t::jsonb;
exception when others then
    return null;
end $$;

comment on function jsonb_or_null(text) is
    'Parse text as jsonb, or null if it will not parse. Lets a view over Parts."Process" survive '
    'one malformed routing instead of failing for every part.';

-- ---------------------------------------------------------------------
-- 2. The cost itself
-- ---------------------------------------------------------------------

create table if not exists process_cost (
    id                   bigint generated by default as identity primary key,
    part_no              text           not null,
    process_name         text           not null,
    cost_per_pcs         numeric(12,4)  not null,
    remarks              text,
    created_at           timestamptz    not null default now(),
    updated_at           timestamptz    not null default now(),
    updated_by           text,
    updated_by_position  text,

    constraint process_cost_part_no_ck      check (btrim(part_no) <> ''),
    constraint process_cost_process_name_ck check (btrim(process_name) <> ''),
    -- Zero is allowed and means something: a step done in-house at no charged cost, deliberately
    -- entered as such. It is not the same as no row, which means nobody has costed it yet, and
    -- the screens keep the two apart. Negative is not a cost.
    constraint process_cost_amount_ck       check (cost_per_pcs >= 0)
);

comment on table process_cost is
    'Cost per piece of one process on one part number. Keyed by part number rather than by Parts '
    'row, so all revisions of a part share a cost until somebody changes it. A missing row means '
    'uncosted; a row of 0 means costed at nothing. Never sum this table without also counting the '
    'steps that have no row - see v_part_cost_summary.';

comment on column process_cost.part_no is
    'Parts."Part_Number", trimmed. Not a foreign key: Parts has no unique constraint on '
    'Part_Number (235 rows, 220 numbers) so there is nothing to reference. The entry screen only '
    'offers numbers that are on the master.';
comment on column process_cost.process_name is
    'One entry of that part''s Parts."Process" array, trimmed. Matched case-insensitively, '
    'because the routings hold both [HARDEN] and [HARDEN ] and they are one process.';
comment on column process_cost.cost_per_pcs is
    'Currency amount per piece, 4 decimal places. Four rather than two because a stamping step '
    'costed at RM 0.0125 rounds to a cent at two and the error is then multiplied by the order '
    'quantity. Rounding happens when a total is displayed, not when a rate is stored.';
comment on column process_cost.updated_by is
    'Name from EmployeeTable of whoever last wrote this row, copied by the page. The same pattern '
    'as tools_txn.txn_by and Data_IPQC.sa_by, and for the same reason: this application has no '
    'Supabase Auth session, so uid() is always null and the database cannot name anybody itself.';

-- Case-folded and trimmed, so [HARDEN], [HARDEN ] and [Harden] cannot become three costs for one
-- step. The stored spelling is left exactly as it was typed - this constrains what is a
-- duplicate, it does not rewrite what anybody entered.
create unique index if not exists process_cost_part_proc_uidx
    on process_cost (btrim(part_no), upper(btrim(process_name)));

comment on index process_cost_part_proc_uidx is
    'One cost per part number per process. Folds case and trailing whitespace because the '
    'routings in Parts."Process" contain both spellings of eleven process names.';

-- The read both screens make: every cost for one part, to lay against its routing.
create index if not exists process_cost_part_idx on process_cost (part_no);

-- ---------------------------------------------------------------------
-- 3. What changed, and who changed it
-- ---------------------------------------------------------------------
--
-- A cost per piece is a number that decisions get made against, so a quiet edit is the failure
-- worth designing away. Every insert, change and deletion lands here, and nothing deletes from
-- here - the trail outlives the row it describes, which is why cost_id is nullable rather than a
-- cascading foreign key.

create table if not exists process_cost_history (
    id                    bigint generated by default as identity primary key,
    cost_id               bigint,
    part_no               text        not null,
    process_name          text        not null,
    action                text        not null check (action in ('INSERT','UPDATE','DELETE')),
    old_cost_per_pcs      numeric(12,4),
    new_cost_per_pcs      numeric(12,4),
    changed_by            text,
    changed_by_position   text,
    changed_at            timestamptz not null default now()
);

comment on table process_cost_history is
    'Append-only trail of every change to process_cost. Read to answer "who set this and when", '
    'not to value a job at a historic cost - calculations always use the live figure in '
    'process_cost. cost_id is deliberately not a foreign key so the trail survives the deletion '
    'of the row it records.';
comment on column process_cost_history.changed_by is
    'Copied from process_cost.updated_by at the moment of the change. On a DELETE that is '
    'whoever the page stamped onto the row immediately before removing it - the delete screen '
    'writes updated_by first for exactly this reason, because a DELETE statement carries no name '
    'of its own.';

create index if not exists process_cost_history_part_idx
    on process_cost_history (part_no, changed_at desc);

-- ---------------------------------------------------------------------
-- 4. Triggers: normalise on the way in, log on the way past
-- ---------------------------------------------------------------------

create or replace function process_cost_normalise() returns trigger
    language plpgsql as $$
begin
    new.part_no      := btrim(new.part_no);
    new.process_name := btrim(new.process_name);
    new.remarks      := nullif(btrim(coalesce(new.remarks, '')), '');
    new.updated_at   := now();
    return new;
end $$;

comment on function process_cost_normalise() is
    'Trims the two key columns before they are stored, so the uniqueness index and every lookup '
    'agree on what the key is regardless of what was typed or pasted.';

drop trigger if exists process_cost_normalise_trg on process_cost;
create trigger process_cost_normalise_trg
    before insert or update on process_cost
    for each row execute function process_cost_normalise();

create or replace function process_cost_log() returns trigger
    language plpgsql as $$
begin
    if tg_op = 'INSERT' then
        insert into process_cost_history
            (cost_id, part_no, process_name, action,
             old_cost_per_pcs, new_cost_per_pcs, changed_by, changed_by_position)
        values (new.id, new.part_no, new.process_name, 'INSERT',
                null, new.cost_per_pcs, new.updated_by, new.updated_by_position);
        return new;

    elsif tg_op = 'UPDATE' then
        -- Only when something a reader would care about actually moved. The delete path below
        -- writes updated_by first and nothing else, and that stamp must not itself become a
        -- history row saying the cost changed when it did not.
        if new.cost_per_pcs is distinct from old.cost_per_pcs
           or new.remarks is distinct from old.remarks then
            insert into process_cost_history
                (cost_id, part_no, process_name, action,
                 old_cost_per_pcs, new_cost_per_pcs, changed_by, changed_by_position)
            values (new.id, new.part_no, new.process_name, 'UPDATE',
                    old.cost_per_pcs, new.cost_per_pcs, new.updated_by, new.updated_by_position);
        end if;
        return new;

    else
        insert into process_cost_history
            (cost_id, part_no, process_name, action,
             old_cost_per_pcs, new_cost_per_pcs, changed_by, changed_by_position)
        values (null, old.part_no, old.process_name, 'DELETE',
                old.cost_per_pcs, null, old.updated_by, old.updated_by_position);
        return old;
    end if;
end $$;

drop trigger if exists process_cost_log_trg on process_cost;
create trigger process_cost_log_trg
    after insert or update or delete on process_cost
    for each row execute function process_cost_log();

-- ---------------------------------------------------------------------
-- 5. The routing, with its costs against it
-- ---------------------------------------------------------------------
--
-- One row per part row per routing step, in routing order. This is the shape both screens read
-- and the shape a report would want; neither has to know that Parts."Process" is a JSON array in
-- a text column.
--
-- security_invoker so the view is not a way around the policies in section 7.

drop view if exists v_joborder_wip_cost;
drop view if exists v_part_cost_summary;
drop view if exists v_part_process_cost;

create view v_part_process_cost
    with (security_invoker = true) as
select p.id                              as part_row_id,
       btrim(p."Part_Number")            as part_no,
       p."Part_Name"                     as part_name,
       p."Revision"                      as revision,
       s.ord::int                        as step_no,
       btrim(s.process_name)             as process_name,
       c.id                              as cost_id,
       c.cost_per_pcs,
       c.remarks                         as cost_remarks,
       c.updated_by                      as cost_updated_by,
       c.updated_at                      as cost_updated_at,
       (jsonb_or_null(p."Process") is not null) as routing_readable
  from "Parts" p
  -- left, so a part whose routing will not parse still appears - with one row, a null step and
  -- routing_readable false. Dropping it would make a broken routing look like a part with no
  -- processes, which is a different and much quieter fault.
  left join lateral jsonb_array_elements_text(jsonb_or_null(p."Process"))
       with ordinality as s(process_name, ord) on true
  left join process_cost c
         on c.part_no = btrim(p."Part_Number")
        and upper(c.process_name) = upper(btrim(s.process_name));

comment on view v_part_process_cost is
    'Parts."Process" unpacked into one row per routing step, in order, with the cost for that '
    'step joined on. cost_per_pcs null means the step has not been costed - which is not zero. '
    'Costs join on part number, so every revision of a part shows the same figure for the same '
    'process name.';

grant select on v_part_process_cost to anon, authenticated;

-- ---------------------------------------------------------------------
-- 6. Two rollups
-- ---------------------------------------------------------------------
--
-- The whole risk in a costing screen is a total that looks complete and is not. sum() skips
-- nulls, so a part with four costed steps out of nine produces a confident-looking number that is
-- missing five processes. Every total below therefore travels with the count that qualifies it,
-- and fully_costed states the answer outright so no reader has to compare two columns to notice.

create view v_part_cost_summary
    with (security_invoker = true) as
select part_row_id,
       part_no,
       max(part_name)                            as part_name,
       max(revision)                             as revision,
       count(process_name)::int                  as steps,
       count(cost_id)::int                       as steps_costed,
       (count(process_name) - count(cost_id))::int as steps_uncosted,
       coalesce(sum(cost_per_pcs), 0)::numeric(12,4) as cost_per_pcs_total,
       (count(process_name) > 0
        and count(process_name) = count(cost_id)) as fully_costed,
       bool_and(routing_readable)                as routing_readable
  from v_part_process_cost
 group by part_row_id, part_no;

comment on view v_part_cost_summary is
    'One row per Parts row: how many routing steps it has, how many are costed, and what the '
    'costed ones add up to per piece. cost_per_pcs_total is only the whole cost of the part when '
    'fully_costed is true - otherwise it is the cost of the steps entered so far and steps_uncosted '
    'says how many are missing.';

grant select on v_part_cost_summary to anon, authenticated;

-- Work in progress, from the job orders that are actually open.
--
-- THE UNIT IS THE JOB ORDER AND THE PART, NOT THE JOB ORDER. 141 JO numbers cover 210 job/part
-- units, because 34 of those numbers carry more than one part and 28 carry more than one
-- quantity. Grouping by JO_Number alone would add unrelated parts together and take one of their
-- quantities to multiply the result by.
--
-- WHAT COUNTS AS DONE. "Status" = 'Completed' on the JobOrder row for that step. That column is
-- the QC-completion flag, not the production one - 2026-07-28_joborder_production_progress.sql
-- added produced_qty and production_completed_at for production - but produced_qty is 0 on all
-- 898 rows because daily output is not in use, so it is the only signal that exists. When daily
-- output is running, partial value at a step becomes possible and this view is where that goes.
-- The screen says which signal it used.

create view v_joborder_wip_cost
    with (security_invoker = true) as
with steps as (
    select j."JO_Number"                                              as jo_number,
           j."Part_Name"                                              as part_name,
           -- The part number is the last parenthesised group of Part_Name. It resolves on 843 of
           -- the 898 rows; the rest nest brackets inside brackets - "PIVOT RING (12.20) (100_PRING
           -- ...(12.2MM B/HOLE))" - and are left null rather than guessed at, so they surface as
           -- uncosted rather than as somebody else's cost.
           btrim(substring(j."Part_Name" from '\(([^()]+)\)\s*$'))    as part_no,
           btrim(j."Process")                                         as process_name,
           -- "Quantity" is text. All 898 rows parse today; one that does not yields null, and the
           -- job shows no value rather than failing the view for every other job.
           case when btrim(coalesce(j."Quantity", '')) ~ '^[0-9]+(\.[0-9]+)?$'
                then btrim(j."Quantity")::numeric end                 as qty,
           (j."Status" = 'Completed')                                 as step_done,
           j.completed_at,
           c.id                                                       as cost_id,
           c.cost_per_pcs
      from "JobOrder" j
      left join process_cost c
             on c.part_no = btrim(substring(j."Part_Name" from '\(([^()]+)\)\s*$'))
            and upper(c.process_name) = upper(btrim(j."Process"))
)
select jo_number,
       part_name,
       part_no,
       max(qty)                                             as qty,
       -- Two quantities under one job and part is a data-entry fault, not a state to design for.
       -- Flagged rather than resolved: it is 2 of 210 units today.
       (min(qty) is distinct from max(qty))                 as qty_inconsistent,
       count(*)::int                                        as steps,
       count(*) filter (where step_done)::int               as steps_done,
       count(cost_id)::int                                  as steps_costed,
       count(*) filter (where step_done and cost_id is null)::int as steps_done_uncosted,

       -- Value added per piece by the steps already finished, and by the whole routing.
       coalesce(sum(cost_per_pcs) filter (where step_done), 0)::numeric(12,4) as cost_per_pcs_done,
       coalesce(sum(cost_per_pcs), 0)::numeric(12,4)                          as cost_per_pcs_all,

       -- The two figures somebody actually asks for. WIP is what the floor is holding: quantity
       -- times the processing already put into it. Full value is what it will have cost when the
       -- last step is signed off.
       (max(qty) * coalesce(sum(cost_per_pcs) filter (where step_done), 0))::numeric(14,2)
                                                            as wip_value,
       (max(qty) * coalesce(sum(cost_per_pcs), 0))::numeric(14,2)
                                                            as full_value,

       (count(*) = count(*) filter (where step_done))       as all_done,
       (count(*) = count(cost_id))                          as fully_costed,
       max(completed_at)                                    as last_completed_at
  from steps
 group by jo_number, part_name, part_no;

comment on view v_joborder_wip_cost is
    'One row per job order and part - not per job order, because 34 of the 141 JO numbers carry '
    'more than one part. wip_value is quantity times the per-piece cost of the process steps '
    'already marked Completed; full_value is the same against the whole routing. Both are only '
    'the whole truth when fully_costed is true, and steps_done_uncosted says how many finished '
    'steps contributed nothing because nobody has costed them.';

comment on column v_joborder_wip_cost.wip_value is
    'Processing value the floor is holding for this job. Excludes material - this system costs '
    'processes, and raw material lives in RawMaterialStock. A job with no completed step is '
    'genuinely 0 here: released, but no process value added yet.';

grant select on v_joborder_wip_cost to anon, authenticated;

-- ---------------------------------------------------------------------
-- 7. RLS: grant the application's anon role
-- ---------------------------------------------------------------------
--
-- Same shape as 2026-08-05_tooling_access.sql section 5, and for the same reason: this app has no
-- Supabase Auth session and arrives on the shared anon key, so `to authenticated` policies
-- evaluate false and every read returns []. Authorisation stays where this application has always
-- put it - the access-level check in the page. See NOTE 2.
--
-- process_cost_history is readable and insertable but deliberately has no update or delete policy.
-- The trigger's insert runs as the definer of nothing in particular, so it needs the insert; a
-- trail that anyone can edit is not a trail.

alter table process_cost         enable row level security;
alter table process_cost_history enable row level security;

drop policy if exists process_cost_read  on process_cost;
drop policy if exists process_cost_write on process_cost;
create policy process_cost_read  on process_cost
    for select to anon, authenticated using (true);
create policy process_cost_write on process_cost
    for all    to anon, authenticated using (true) with check (true);

drop policy if exists process_cost_history_read   on process_cost_history;
drop policy if exists process_cost_history_insert on process_cost_history;
create policy process_cost_history_read   on process_cost_history
    for select to anon, authenticated using (true);
create policy process_cost_history_insert on process_cost_history
    for insert to anon, authenticated with check (true);

grant select, insert, update, delete on process_cost         to anon, authenticated;
grant select, insert                 on process_cost_history to anon, authenticated;
grant usage, select on sequence process_cost_id_seq         to anon, authenticated;
grant usage, select on sequence process_cost_history_id_seq to anon, authenticated;

commit;

-- PostgREST caches the schema; without this the new tables and views 404 until the container
-- restarts.
notify pgrst, 'reload schema';

-- =====================================================================
--  NOTES
-- =====================================================================
--
-- NOTE 1 - the routings this will not cost cleanly, and why they are left alone.
--   * 92 distinct process names across 1,117 steps, and some of them are the same process:
--     SWISS AUTO LATHE / SWISS AUTO-LATHE / SWISS AUTO LATHE MACHINING / SWISS AUTO-LATHE
--     MACHINING; POLISH and POLISHING; TURN MILL and TURNMILL. The trim and case-fold above
--     collapse whitespace and capitals, nothing more - these are four different strings and each
--     needs its own cost on each part that uses it. Merging them is a decision about the shop,
--     not about a database, and it belongs in the part master where the routings are edited.
--   * "faiz test again" appears on 4 routing steps and "v4_TEST" is a job order part. Test data
--     in the master, costable like anything else, not this file's business to delete.
--   * 55 of the 898 JobOrder rows have no resolvable part number because Part_Name nests brackets
--     inside brackets. They appear in v_joborder_wip_cost with a null part_no and no costs, which
--     is the honest answer; naming them would need somebody to say which part each one is.
--
-- NOTE 2 - what the RLS grant costs.
--   Anyone holding the anon key (it ships in assets/app-config.js) can read and write these
--   tables directly, bypassing the page - including the cost figures. That is already true of
--   Parts, JobOrder, SalesOrders and the tooling and gauge tables; this makes costing consistent
--   with them rather than introducing anything new. If cost should be held to a higher standard
--   than the rest of the app, the fix is a real Supabase Auth session and these policies revert
--   to `to authenticated`.
--
-- NOTE 3 - verify:
--   select count(*) from v_part_process_cost;                          -- 1117
--   select count(*) from v_part_cost_summary;                          -- 235
--   select count(*) from v_part_cost_summary where fully_costed;       -- 0, until costs are entered
--   select count(*) from v_joborder_wip_cost;                          -- 210
--   select count(*) from v_joborder_wip_cost where not all_done;       -- 50
--   select count(*) from v_joborder_wip_cost where part_no is null;    -- 17 (the nested-bracket names:
--                                                                     --     55 rows, 9 spellings, 17 job/part units)
--   select sum(wip_value) from v_joborder_wip_cost where not all_done; -- 0, until costs are entered
--   -- the trim and case-fold actually hold:
--   insert into process_cost (part_no, process_name, cost_per_pcs) values ('  TESTPN ', ' harden ', 1);
--   insert into process_cost (part_no, process_name, cost_per_pcs) values ('TESTPN', 'HARDEN', 2);
--                                                                      -- second one fails, 23505
--   select part_no, process_name from process_cost where part_no = 'TESTPN';   -- TESTPN | harden
--   select action, old_cost_per_pcs, new_cost_per_pcs from process_cost_history
--    where part_no = 'TESTPN';                                         -- INSERT | null | 1.0000
--   delete from process_cost where part_no = 'TESTPN';                 -- leaves the DELETE row behind
